stages:
  - check-format
  - build
  - test
  - setup-repo
  - test-installers1
  - test-installers2
  - deploy
  - deploy-pypi

default:
  image: $DOCKER_REGISTRY/rewriting/templates/cpp/ubuntu20
  tags: ["kubernetes"]

.conan_template: &conan_template |
  conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
  conan remote add gitlab ${CI_API_V4_URL}/packages/conan
  conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}

check-format:
  stage: check-format
  script:
    - pre-commit install-hooks
    - pre-commit run --all-files --show-diff-on-failure

build:
  stage: build
  needs: [check-format]
  image: $DOCKER_REGISTRY/rewriting/mc-asm/llvm11
  artifacts:
    paths:
      - build/
  script:
    - *conan_template
    - mkdir build
    - cd build
    - conan install .. --remote=gitlab
    - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - make
    - cpack -G DEB -D CPACK_MCASM_DEBIAN_PACKAGE=lib -D CPACK_DEBIAN_PACKAGE_ARCHITECTURE=amd64
    - cpack -G DEB -D CPACK_MCASM_DEBIAN_PACKAGE=lib-dbg -D CPACK_DEBIAN_PACKAGE_ARCHITECTURE=amd64
    - cpack -G DEB -D CPACK_MCASM_DEBIAN_PACKAGE=dev -D CPACK_DEBIAN_PACKAGE_ARCHITECTURE=amd64
    - cpack -G DEB -D CPACK_MCASM_DEBIAN_PACKAGE=driver -D CPACK_DEBIAN_PACKAGE_ARCHITECTURE=amd64
    - cpack -G DEB -D CPACK_MCASM_DEBIAN_PACKAGE=driver-dbg -D CPACK_DEBIAN_PACKAGE_ARCHITECTURE=amd64

build-windows:
  stage: build
  tags: [mcasm-windows]
  artifacts:
    paths:
      - mcasm-*.whl
      - mcasm-*-win64
  script:
    - systeminfo
    - env
    - mkdir build
    - cd build
    - pip3 install twine wheel setuptools --upgrade
    - cmd.exe /C "C:\\VS\\VC\\Auxiliary\\Build\\vcvars64.bat && conan install .."
    - cmd.exe /C "C:\\VS\\VC\\Auxiliary\\Build\\vcvars64.bat && cmake -G Ninja -DPYTHON=C:\\Python39\\python.exe -DCMAKE_BUILD_TYPE=RelWithDebInfo .."
    - cmd.exe /C "C:\\VS\\VC\\Auxiliary\\Build\\vcvars64.bat && ninja"
    - cmd.exe /C "C:\\VS\\VC\\Auxiliary\\Build\\vcvars64.bat && ninja python-wheel"
    - cmd.exe /C "C:\\VS\\VC\\Auxiliary\\Build\\vcvars64.bat && ctest -V"
    - cmd.exe /C "C:\\VS\\VC\\Auxiliary\\Build\\vcvars64.bat && C:\\PROGRA~1\\CMake\\bin\\cpack.exe -G ZIP"
    - ZIP_FILE=(mcasm-*-win64.zip)
    - BASE_DIRECTORY="${ZIP_FILE%.*}"
    - unzip $ZIP_FILE
    - cp python/dist/mcasm-*.whl ../
    - cp bin/*.pdb $BASE_DIRECTORY/bin/
    - cp -r $BASE_DIRECTORY ../

test:
  stage: test
  needs: [build]
  image: $DOCKER_REGISTRY/rewriting/mc-asm/llvm11
  script:
    - cd build
    - ctest -V

setup-repo:
  stage: setup-repo
  needs: [build, test]
  artifacts:
    paths:
      - installers/
  script:
    - mkdir installers/
    - cp build/*.deb installers/
    - cp src/driver.cpp installers/
    - cd installers/ && dpkg-scanpackages . /dev/null > Packages

test-driver:
  stage: test-installers1
  needs: [setup-repo]
  script:
    - echo -e "\ndeb [trusted=yes] file:$(pwd)/installers/ ./\n" >> /etc/apt/sources.list
    - apt-get update -y
    - apt-get install -y mcasm-driver
    - echo "ud2" | mcasm --target x86_64-linux-gnu - | grep "0f0b"

test-driver-dbg:
  stage: test-installers1
  needs: [setup-repo]
  script:
    - 'echo -e "\ndeb [trusted=yes] file:$(pwd)/installers/ ./\n" >> /etc/apt/sources.list'
    - apt-get update -y
    - apt-get install -y mcasm-driver mcasm-driver-dbg
    - '[ -f /usr/lib/debug/.build-id/$(readelf -n /usr/bin/mcasm | grep "Build ID: " | cut -d":" -f2 | sed -E "s/ ([a-f0-9]{2,})([a-f0-9]{30,})/\1\/\2/g").debug ]'

test-dev:
  stage: test-installers1
  needs: [setup-repo]
  artifacts:
    paths:
      - test-install
  script:
    - echo -e "\ndeb [trusted=yes] file:$(pwd)/installers/ ./\n" >> /etc/apt/sources.list
    - apt-get update -y
    - apt-get install -y libmcasm-dev
    - gcc test/test_lib.c -o test-install -lmcasm
    - ./test-install

test-lib:
  stage: test-installers2
  needs: [setup-repo, test-dev]
  script:
    - echo -e "\ndeb [trusted=yes] file:$(pwd)/installers/ ./\n" >> /etc/apt/sources.list
    - apt-get update -y
    - apt-get install -y libmcasm-dev
    - ./test-install

test-lib-dbg:
  stage: test-installers1
  needs: [setup-repo]
  script:
    - 'echo -e "\ndeb [trusted=yes] file:$(pwd)/installers/ ./\n" >> /etc/apt/sources.list'
    - apt-get update -y
    - apt-get install -y libmcasm libmcasm-dbg
    - '[ -f /usr/lib/debug/.build-id/$(readelf -n /usr/lib/libmcasm.so | grep "Build ID: " | cut -d":" -f2 | sed -E "s/ ([a-f0-9]{2,})([a-f0-9]{30,})/\1\/\2/g").debug ]'

deploy:
  stage: deploy
  needs: [setup-repo, test-driver, test-dev, test-lib]
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - '*mcasm*.deb'
    expire_in: 1 week
  script:
    - cp installers/*.deb ./

python-wheel:
  stage: deploy
  needs: [build]
  image: $DOCKER_REGISTRY/rewriting/mc-asm/llvm11
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - mcasm-*-py*-*-*.whl
    expire_in: 1 week
  script:
    - pip3 install twine wheel setuptools --upgrade
    - make -t -C build
    - make -C build python-wheel
    - auditwheel repair build/python/dist/*.whl -w build/python/dist/wheelhouse
    - cp build/python/dist/wheelhouse/*.whl ./

python-wheel-pypi:
  stage: deploy-pypi
  needs: [python-wheel, build-windows]
  only: [master]
  image: $DOCKER_REGISTRY/rewriting/mc-asm/llvm11
  script:
    - pip3 install mcasm-*manylinux2010_x86_64.whl
    - VERSION=$(python3 -c "import mcasm; print(mcasm.__version__)")
    - RESPONSE_CODE=$(curl -Ls -o /dev/null -w "%{http_code}" https://pypi.org/project/mcasm/${VERSION}/)
    - if [ "$RESPONSE_CODE" = "404" ];
      then
        pip3 install twine --upgrade;
        twine check mcasm-*.whl;
        twine upload mcasm-*.whl -u __token__ -p $PYPI_API_KEY;
      fi

python-wheel-internal-pypi:
  stage: deploy-pypi
  needs: [python-wheel, build-windows]
  only: [master]
  image: $DOCKER_REGISTRY/rewriting/mc-asm/llvm11
  script:
    - pip3 install twine wheel setuptools --upgrade
    - twine check mcasm-*.whl
    - echo 0 > exitcode.txt
    - (twine upload --verbose --repository-url $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi --username gitlab-ci-token --password "$CI_JOB_TOKEN" mc-asm*.whl | tee response.txt) || (echo $? > exitcode.txt; exit 0)
    # do not fail if we try to re-upload a package of the same version
    - if [[ "$(cat exitcode.txt)" != 0 && -z "$(cat response.txt | grep "File name has already been taken")" ]];
      then
        exit 1;
      fi

conan_package:
  stage: build
  image: $DOCKER_REGISTRY/rewriting/mc-asm/llvm11
  script:
    - *conan_template
    - export CONAN_PACKAGE="mcasm/0.1@"$(echo ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} | sed -e "s/\\//+/g")/stable
    - conan create --remote=gitlab . ${CONAN_PACKAGE}
    - conan upload ${CONAN_PACKAGE} --all --remote=gitlab
